### ISSUE TITLE
Shows page Titles crop weird on mobile

### ISSUE THREAD

**Issue by iChris** [GoodStuff-Fm/goodstuff#44]
The [shows](https://goodstuff.fm/shows/) page is funky on mobile.

<img width="371" alt="Screen Shot 2020-01-26 at 15 56 18" src="https://user-images.githubusercontent.com/2054478/73143932-70ac6c00-4054-11ea-8687-692da81836f9.png">

**Comment by kyleroderick** [comment]
This is fixed 😄
